language: go

go:
  - 1.5.3

install:  
  - go get github.com/Sirupsen/logrus  
  - go get github.com/boltdb/bolt/...
  - go get github.com/oschwald/geoip2-golang
  - go get github.com/mvdan/xurls

script:
  - go test -tags=integration -v ./...